# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Proctractor CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with: 
          path: Protractor_workspace
    - name: Running Protractor Test Cases ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: Install npm dependencies
      run: |
        cd ${{ github.workspace }}/Protractor_workspace/
        ls -lah
        npm install pm2 -g
        npm i
    - name: Bring up selenium webdriver.
      run: |
        cd ${{ github.workspace }}/Protractor_workspace/
        pm2 start "npm run setup" --name webdriverS --watch -l ./webdriver
        sleep 10s
    - name: Run Protractor Test Cases
      run: |
        cd ${{ github.workspace }}/Protractor_workspace/
        npm run execute
        
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: webdriver
        path: webdriver/**
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: beautiful-reports
        path: target/beautiful-reports/**
